---
title: "Investigating the use of learning mechanisms in a species that is rapidly expanding its geographic range"
author: "Dr. Kelsey McCune (University of California Santa Barbara), [Dr. Richard McElreath](http://xcelab.net/rm/) (Max Planck Institute for Evolutionary Anthropology), [Dr. Corina Logan](http://CorinaLogan.com) (Max Planck Institute for Evolutionary Anthropology, corina_logan@eva.mpg.de)"
date: "`r Sys.Date()`"
output:
  html_document: 
    toc: true
    toc_depth: 4
    toc_float: 
      collapsed: false
    code_folding: hide 
  md_document: 
    toc: true
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
  github_document: 
    toc: true
bibliography: /Users/corina/GitHub/grackles/Files/MyLibrary.bib
---

***Click [here](https://github.com/corinalogan/grackles/blob/master/README.md) to navigate to the version-tracked reproducible manuscript (.Rmd file)***

###ABSTRACT

This is one of many studies planned for our long-term research on the role of behavioral flexibility in rapid geographic range expansions. **Project background:** Behavioral flexibility, the ability to change behavior when circumstances change based on learning from previous experience (@mikhalevich_is_2017), is thought to play an important role in a species' ability to successfully adapt to new environments and expand its geographic range (e.g., [@lefebvre1997feeding], [@griffin2014innovation], [@chow2016practice], [@sol2000behavioural], [@sol2002behavioural], [@sol2005big]). However, behavioral flexibility is rarely directly tested at the individual level, thus limiting our ability to determine how it relates to other traits, which limits the power of predictions about a species' ability to adapt behavior to new environments. We use great-tailed grackles (a bird species) as a model to investigate this question because they have rapidly expanded their range into North America over the past 140 years ([@wehtje2003range], [@peer2011invasion]) (see an overview of the [5-year project timeline](https://github.com/corinalogan/grackles/blob/master/README.md)). **This investigation**: In this piece of the long-term project, we aim to determine what learning mechanisms grackles use (i.e., stimulus or local enhancement, imitation/emulation, personal information) when learning to solve a foraging problem. We will use a puzzle box apparatus that contains food accessible via diverse opening methods. Wild grackles will first be habituated to eating from or off of the non-functional apparatus so that differences in neophobia will not confound performance. We will test grackles from a population in the middle of the expanded geographic range to determine whether this species uses social learning. If so, then we will compare performance across three populations (core, middle of the expansion, and at the northern range edge). Results will indicate how social learning might play a role in the geographic range expansion by elucidating how this species solves novel foraging problems in the wild.  

###A. STATE OF THE DATA
This preregistration was written (2017) prior to collecting data. 

###B. HYPOTHESIS

#### H1: Information about resources is obtained via individual learning and also transmitted socially in the wild.

Prediction 1: Stimulus enhancement will draw attention to WHAT locus on the apparatus to attend to, and then subjects will rely on personal information to learn HOW to solve that locus. This was found for a similar study on New Caledonian crows (@logan2016new). We predict that it will be the same for the grackles because grackles likely need to pay attention to what resources others are accessing, but the exact details of how to access these resources may not be as important because it is likely that most resources are not very complicated to access (e.g., open a sandwich bun wrapper to eat the sandwich)

P1 alternative 1: Subjects might rely on local enhancement to attend to a particular area and then rely on personal information to explore the area and learn how to solve a particular locus. Grackles may pay more attention to other grackles when determing whether to visit a location to search for food rather than to whatever food might be present in that location.

P1 alternative 2: Subjects copy (copy partly suggests emulation, or copy completely suggests imitation) the sequence of actions they observed others using to solve a particular locus. This may be particularly useful mechanism when trying to open complicated packaging (e.g., a plastic ketchup packet). Complicated packaging is likely not as frequently encountered in their natural environment, which is full of easier to access food such as insects.

P1 alternative 3: Subjects do not use social information and rely solely on personal information when solving novel apparatus loci. This species does not form strong bonds with each other (relative to, for example, monogamous corvids), therefore perhaps social information is not as important to them when solving new problems.

P2: Dominant individuals will solve faster because they can exclude subordinates from accessing the resource. This might also make it appear that males are faster at solving than females because males are reported as more dominant than females.

P3: Older individuals may be better at outcompeting others potentially because they have more experience at solving problems in general. We will be able to test this prediction when comparing juveniles (<1yr) and adults (>1yr), but we will not know the age of the adults unless they were banded as juveniles and became adults by the time the testing occurred. Therefore we will have a limited ability to test this prediction. 

P4: It does not require many observations of others attempting to solve or solving at a particular locus to influence which loci observers attempt first. This was found for a similar study on New Caledonian crows (@logan2016new). We predict that it will be the same for the grackles because grackles likely need to attend to fleeting observations of others as they figure out how to find food in their shared environment. Therefore, there is pressure to attend to any available information.

#### H2: Performance on the learning task will vary among grackles in the different populations included in this study (core, middle of the expansion, and at the range edge).

P5: Individuals from the population on the edge of the grackle range will solve more options faster and rely more on social learning than grackles from the middle of the expanded range, and the original core of the range. This may occur because social information is particularly useful to individuals in novel environments (e.g., the social learning strategy of "copy when uncertain" [@laland2004social]).

P5 alternative 1: Individuals from the population in the core of the grackle range will solve more options faster and rely more on social information than grackles from the middle and the edge of the expanded range. This may occur because the lack of novelty in the endemic range may result in selection on efficient individual learning (i.e., producers) which leads to the production of high quality public social information. When all social information is of a high quality, individuals may be selected to use it when it is available ([@laland2004social]).

P5 alternative 2: Individuals from the the middle of the expanded range will solve more options faster and rely more on social information than grackles from the population on the edge of the grackle range, and the original core of the range. This is potentially because population densities might be higher in the middle of the expanded range, therefore there might be more within-species competition for resources.

P5 alternative 3: There will be no difference in the number of options solved, the rate of solving, and the reliance on personal versus social information on the social learning task across grackle populations. This is potentially because grackles in each population are equally social and generalist foragers ([@levebvre1996is]), measured in a separate preregistration (http://corinalogan.com/Preregistrations/g_flexforaging.html) and rely on a mixture of personal and social information.

###C. METHODS

**Planned Sample**
	
Great-tailed grackles will be caught in the wild in Tempe, Arizona USA for individual identification (colored leg bands in unique combinations) until as much of the population is banded as possible (estimated 400 grackles in the area, 56 have been banded as of 6 May 2019). Some individuals (~6-16) will be brought temporarily into aviaries where demonstrators will be trained on a particular locus of the apparatus before being released back to the wild to serve as demonstrators for the experiment, which will occur in the wild (in the same way as @logan2016new, except in the wild).

**Data collection stopping rule**
	
Eight sessions of up to 45 minutes per group will be conducted. A group is defined as having the same trained demonstrator in the presence of many of the same conspecifics across the sessions. For control groups (those with no trained demonstrator), a group must have many of the same individuals as in the first session. We will stop this experiment after each group has completed 8 sessions or when we must move to the next field site, whichever comes first.

####**Randomization and counterbalancing** 

In the population in the middle of the expanded range, we will attempt to counterbalance demonstrators among the three groups such that each group will observe a demonstrator that was trained in a distinct solving method, and observers in each group will not be exposed to other demonstrators using different opening methods. We will counterbalance the core and edge populations by training demonstrators on one solving method in each group (1 group per population) such that the core population demonstrators will be trained on one solving method, and the edge demonstrators will be trained in a different solving method.

####**Blinding of conditions during analysis**

No blinding is involved in this study.

####**Dependent variables**

1) Latency to attempt to solve a particular locus

2) Latency to solve (obtain the food) a particular locus

####**Independent variables**

####*P1-P5*

1) Locus on the apparatus (horizontal side, horizontal flap, vertical flap, or vertical rubber)

2) ID

3) Group ID

4) Start and end times for attempting/solving and observations of attempts/solves (minutes:seconds since the beginning of the session)

5) Whether the observer saw another individual succeed (obtain food) or just attempt (did not obtain food) at the locus the observer is watching

6) Which apparatus (left or right) was observed or interacted with

7) Sex

8) Age

9) Dominance rank

10) Population (center, middle, edge)

11) Random effect: ID (to allow for multiple events from the same individual)

###D. ANALYSIS PLAN

We do not plan to **exclude** any data. When **missing data** occur, the existing data for that individual will be included in the analyses for the tests they completed. Analyses will be conducted in R (current version `r getRversion()`; @rcoreteam). When there is more than one experimenter collecting data, experimenter will be added as a random effect to account for potential differences between experimenters in conducting the tests.

####*Data checking*

The data will be checked for overdispersion, underdispersion, zero-inflation, and heteroscedasticity with the DHARMa R package [@Hartig2019dharma] following methods by [Hartig](https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html). 

####*P1-P4: Learning mechanisms*

The analysis will be conducted as in @logan2016new with a survival analysis (Cox proportional hazards model), using ID as a random effect, that is sensitive to the order and latency of events at each locus. We will model the rate at which individual *i* in group *j* first attempted method *l* at locus *k* as a function of predictor variables (e.g., age, sex, rank). This method accounts for previous attempts by the subject as well as observations of others attempting and solving the loci.

```{r mod, eval=FALSE, warning=FALSE, results='asis', echo=TRUE, include=TRUE}
data1 <- read.csv ("/Users/corina/GTGR/data/data_reverse.csv", header=T, sep=",", stringsAsFactors=F) 

# DATA CHECKING
library(DHARMa)
library(lme4)

#Latency to solve
simulationOutput <- simulateResiduals(fittedModel = MCMCglmm(latencysolve ~ Locus + Group ID + StartTime + ObservedAnother + Apparatus + Sex + Age + Rank + Population + (1|ID), family=poisson, data=data1), n=250) #250 simulations, but if want higher precision change n>1000
simulationOutput$scaledResiduals #Expect a flat distribution of the overall residuals, and uniformity in y direction if plotted against any predictor
testDispersion(simulationOutput) #if under- or over-dispersed, then p-value<0.05, but then check the dispersion parameter and try to determine what in the model could be the cause and address it there, also check for zero inflation
testZeroInflation(simulationOutput) #compare expected vs observed zeros, not zero-inflated if p<0.05
testUniformity(simulationOutput) #check for heteroscedasticity ("a systematic dependency of the dispersion / variance on another variable in the model" Hartig, https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html), which is indicated if dots aren't on the red line and p<0.05. Also...
plot(simulationOutput) #...there should be no pattern in the data points in the right panel
plotResiduals(ReverseNumber, simulationOutput$scaledResiduals) #plot the residuals against other predictors (in cases when there is more than 1 fixed effect) - can't get this code to work yet

#Latency to attempt to solve
simulationOutput <- simulateResiduals(fittedModel = MCMCglmm(latencyattempt ~ Locus + Group ID + StartTime + ObservedAnother + Apparatus + Sex + Age + Rank + Population + (1|ID), family=poisson, data=data1), n=250) #250 simulations, but if want higher precision change n>1000
simulationOutput$scaledResiduals #Expect a flat distribution of the overall residuals, and uniformity in y direction if plotted against any predictor
testDispersion(simulationOutput) #if under- or over-dispersed, then p-value<0.05, but then check the dispersion parameter and try to determine what in the model could be the cause and address it there, also check for zero inflation
testZeroInflation(simulationOutput) #compare expected vs observed zeros, not zero-inflated if p<0.05
testUniformity(simulationOutput) #check for heteroscedasticity ("a systematic dependency of the dispersion / variance on another variable in the model" Hartig, https://cran.r-project.org/web/packages/DHARMa/vignettes/DHARMa.html), which is indicated if dots aren't on the red line and p<0.05. Also...
plot(simulationOutput) #...there should be no pattern in the data points in the right panel
plotResiduals(ReverseNumber, simulationOutput$scaledResiduals) #plot the residuals against other predictors (in cases when there is more than 1 fixed effect) - can't get this code to work yet

```

####*P4: How many observations?*

The analysis will be conducted as in @barrett2017pay using multilevel experience-weighted attraction models that can determine how individuals accumulate experience and the probability of an option being chosen. We will also use this analysis to investigate P1-P3.

###E. ETHICS

This research is carried out in accordance with permits from the:

1) US Fish and Wildlife Service (scientific collecting permit number MB76700A-0,1,2)
2) US Geological Survey Bird Banding Laboratory (federal bird banding permit number 23872)
3) Arizona Game and Fish Department (scientific collecting license number SP594338 [2017], SP606267 [2018], and SP639866 [2019])
4) Institutional Animal Care and Use Committee at Arizona State University (protocol number 17-1594R)

###F. AUTHOR CONTRIBUTIONS

**McCune:** Experimental design, materials, data collection, data analysis and interpretation, editing/revising.

**McElreath:** Analysis design, data analysis and interpretation, editing/revising, funding.

**Logan:** Hypothesis development, experimental design, materials, data collection, data analysis and interpretation, write up.

###G. FUNDING

This research is funded by the Department of Human Behavior, Ecology and Culture at the Max Planck Institute for Evolutionary Anthropology.

###H. ACKNOWLEDGEMENTS

We thank Ben Trumble for providing us with a wet lab at Arizona State University and Angela Bond for lab support; Melissa Wilson Sayres for sponsoring our affiliations at Arizona State University and lending lab equipment; Kevin Langergraber for serving as local PI on the ASU IACUC; Kristine Johnson for technical advice on great-tailed grackles; Jay Taylor for grackle scouting at Arizona State University; Arizona State University School of Life Sciences Department Animal Care and Technologies for providing space for our aviaries and for their excellent support of our daily activities; Julia Cissewski for tirelessly solving problems involving financial transactions and contracts; Richard McElreath for project support; Erin Vogel, our Recommender at PCI Ecology, and Simon Gingins and two anonymous reviewers for their wonderful feedback; and our research assistants: Aelin Mayer, Nancy Rodriguez, Brianna Thomas, Aldora Messinger, Elysia Mamola, Michael Guillen, Rita Barakat, Adriana Boderash, Olateju Ojekunle, August Sevchik, Justin Huynh, Jennifer Berens, and Amanda Overholt.

###I. REFERENCES
